"""add interval to monitors

Revision ID: 064cc4c46c5e
Revises: cbabc257dbfd
Create Date: 2024-04-13 06:08:49.185807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064cc4c46c5e'
down_revision = 'cbabc257dbfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('interval', sa.Integer(), nullable=True))
    op.execute('UPDATE monitors SET interval = 1')
    op.alter_column('monitors', 'interval', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'interval')
    # ### end Alembic commands ###
