"""{}

Revision ID: 0a5b8f3ee8e4
Revises: 627da398ae64
Create Date: 2024-04-14 15:17:57.818247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5b8f3ee8e4'
down_revision = '627da398ae64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('u_blod_preasure_active', 'students_register', type_='unique')
    op.drop_constraint('u_heard_rate_active', 'students_register', type_='unique')
    op.drop_constraint('fk_students_register_blod_preasure_monitor_id', 'students_register', type_='foreignkey')
    op.drop_constraint('fk_students_register_heard_rate_monitor_id', 'students_register', type_='foreignkey')
    op.drop_column('students_register', 'heard_rate_monitor_id')
    op.drop_column('students_register', 'blod_preasure_monitor_id')
    op.drop_column('monitors', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_register', sa.Column('blod_preasure_monitor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('students_register', sa.Column('heard_rate_monitor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('monitors', sa.Column('sku', sa.String(length=50), nullable=False))
    op.create_foreign_key('fk_students_register_heard_rate_monitor_id', 'students_register', 'monitors', ['heard_rate_monitor_id'], ['eui'], ondelete='RESTRICT')
    op.create_foreign_key('fk_students_register_blod_preasure_monitor_id', 'students_register', 'monitors', ['blod_preasure_monitor_id'], ['eui'], ondelete='RESTRICT')
    op.create_unique_constraint('u_heard_rate_active', 'students_register', ['heard_rate_monitor_id', 'active'])
    op.create_unique_constraint('u_blod_preasure_active', 'students_register', ['blod_preasure_monitor_id', 'active'])
    # ### end Alembic commands ###
