"""add students_register_monitors

Revision ID: 627da398ae64
Revises: 9c59ef854f9f
Create Date: 2024-04-13 15:06:50.919101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627da398ae64'
down_revision = '9c59ef854f9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_register_monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_register_id', sa.UUID(), nullable=True),
    sa.Column('monitor_id', sa.UUID(), nullable=True),
    sa.Column('value_xpath', sa.String(length=255), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('end_subtstract', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.eui'], name=op.f('fk_students_register_monitors_monitor_id_monitors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_register_id'], ['students_register.uuid'], name=op.f('fk_students_register_monitors_student_register_id_students_register'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students_register_monitors'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_register_monitors')
    # ### end Alembic commands ###
