"""add rules to students_register

Revision ID: 66c54e0ce509
Revises: cab2cadbc2bd
Create Date: 2024-04-25 03:52:45.243862

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as postgresql


# revision identifiers, used by Alembic.
revision = '66c54e0ce509'
down_revision = 'cab2cadbc2bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column('students_register', sa.Column('rules', postgresql.ARRAY(sa.String()), nullable=True))
    op.execute('UPDATE students_register SET rules = ARRAY[]::varchar[]')
    op.alter_column('students_register', 'rules', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_column('students_register', 'rules')
