"""add monitor_type model

Revision ID: 943ca9d94360
Revises: a3a83ab8bff0
Create Date: 2024-04-21 05:12:09.042542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943ca9d94360'
down_revision = 'a3a83ab8bff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('monitor_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_types')),
    sa.UniqueConstraint('sku', name=op.f('uq_monitor_types_sku')),
    sa.UniqueConstraint('uuid', name=op.f('uq_monitor_types_uuid'))
    )
    op.add_column('monitors', sa.Column('monitor_type_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_monitor_type_id_monitor_types', 'monitors', 'monitor_types', ['monitor_type_id'], ['uuid'], ondelete='RESTRICT')
    op.drop_column('monitors', 'interval')
    op.drop_column('monitors', 'monitor_type')
    op.drop_column('monitors', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('monitors', sa.Column('monitor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('monitors', sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_monitor_type_id_monitor_types', 'monitors', type_='foreignkey')
    op.drop_column('monitors', 'monitor_type_id')
    op.drop_table('monitor_types')
    # ### end Alembic commands ###
