"""add index to monitor_data

Revision ID: a3a83ab8bff0
Revises: 0a5b8f3ee8e4
Create Date: 2024-04-14 20:47:30.759880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a83ab8bff0'
down_revision = '0a5b8f3ee8e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('monitor_data_ts_monitor_id_idx', 'monitor_data', ['monitor_id', sa.text('ts ASC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('monitor_data_ts_monitor_id_idx', table_name='monitor_data')
    # ### end Alembic commands ###
