"""rename end_subtstract for move_end_to

Revision ID: cab2cadbc2bd
Revises: 943ca9d94360
Create Date: 2024-04-21 05:44:47.645366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab2cadbc2bd'
down_revision = '943ca9d94360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_register_monitors', sa.Column('move_end_to', sa.Integer(), nullable=False))
    op.drop_column('students_register_monitors', 'end_subtstract')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_register_monitors', sa.Column('end_subtstract', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('students_register_monitors', 'move_end_to')
    # ### end Alembic commands ###
