"""add ts to monitor_data

Revision ID: cbabc257dbfd
Revises: b90b0efc0cf4
Create Date: 2024-04-12 14:21:08.301650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbabc257dbfd'
down_revision = 'b90b0efc0cf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_data', sa.Column('ts', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_data', 'ts')
    # ### end Alembic commands ###
