"""add unique constraint monitor_data_monitor_id_ts

Revision ID: edeb094ee1fe
Revises: 064cc4c46c5e
Create Date: 2024-04-13 07:57:07.068842

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'edeb094ee1fe'
down_revision = '064cc4c46c5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('u_monitor_data_monitor_id_ts', 'monitor_data', ['monitor_id', 'ts'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('u_monitor_data_monitor_id_ts', 'monitor_data', type_='unique')
    # ### end Alembic commands ###
